### ISSUE TITLE
add docker

### ISSUE THREAD

**Issue by luismavs** [luismavs/ExposureStats#6]

**Comment by Itz-Agasta** [comment]
Hi @luismavs,

I really like your project and have started working on the dockerization issue. However, I ran into a problem, which I’ve detailed in Issue #12. Could you please take a look when you get a chance?

Thank you!

**Comment by luismavs** [comment]
Hi @Itz-Agasta, thanks for the comments. I was actually just working on this project. Check the changes introduced by  PR #13, config setting done now by env vars wich will help in dockerizing.
